version: 2
jobs:
  deploy_production:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "functions/yarn.lock" }}
      - run:
          name: Install functions
          command: yarn
          working_directory: functions
      - save_cache:
          key: dependency-cache-{{ checksum "functions/yarn.lock" }}
          paths:
            - functions/node_modules
      # トップレベルのnpm設定
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Set Environment Variables
          command: |
            echo "REACT_APP_FIREBASE_CONFIG=$REACT_APP_FIREBASE_CONFIG" >> .env
            echo "REACT_APP_REDIRECT_URI=$REACT_APP_REDIRECT_URI" >> .env
            echo "REACT_APP_SPOTIFY_CLIENT_ID=$REACT_APP_SPOTIFY_CLIENT_ID" >> .env
            echo "spotify_client_id=$spotify_client_id" >> .env
            echo "spotify_client_secret=$spotify_client_secret" >> .env
            echo "project_id=$project_id" >> .env
            echo "database_id=$database_id" >> .env
            echo "location_id=$location_id" >> .env
            echo "job_name=$job_name" >> .env
            echo "user_name=$user_name" >> .env
            echo "redirect_uri=$redirect_uri" >> .env
      - run:
          name: Set Firebase Config
          command: yarn set-config
      - run:
          name: Test
          command: yarn test
      - run:
          name: Build
          command: yarn build
      - run:
          name: Deploy
          command: yarn deploy

workflows:
  version: 2
  deploy_master:
    jobs:
      - deploy_production:
          filters:
            branches:
              only: master
