version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      # functions配下のnpm設定
      - restore_cache:
          key: dependency-cache-{{ checksum "functions/yarn.lock" }}
      - run:
          name: Install functions/
          command: yarn
          working_directory: functions
      - save_cache:
          key: dependency-cache-{{ checksum "functions/yarn.lock" }}
          paths:
            - functions/node_modules
      # トップレベルのnpm設定
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Set Environment Variables
          command: |
            echo "REACT_APP_FIREBASE_CONFIG=$REACT_APP_FIREBASE_CONFIG" >> .env
            echo "REACT_APP_REDIRECT_URI=$REACT_APP_REDIRECT_URI" >> .env
            echo "REACT_APP_SPOTIFY_CLIENT_ID=$REACT_APP_SPOTIFY_CLIENT_ID" >> .env
            echo "spotify_client_id=$SPOTIFY_CLIENT_ID" >> .env
            echo "spotify_client_secret=$SPOTIFY_CLIENT_SECRET" >> .env
            echo "project_id=$PROJECT_ID" >> .env
            echo "database_id=$DATABASE_ID" >> .env
            echo "location_id=$LOCATION_ID" >> .env
            echo "job_name=$JOB_NAME" >> .env
            echo "user_name=$USER_NAME" >> .env
            echo "redirect_uri=$REACT_APP_REDIRECT_URI" >> .env
      - run:
          name: Set Firebase Config
          command: yarn set-config
      - run:
          name: Test
          command: yarn test
      - run:
          name: Build
          command: yarn build
      - run:
          name: Deploy
          command: yarn deploy

workflows:
  version: 2
  deploy_master:
    jobs:
      - build:
          filters:
            branches:
              only: master
